sudo: required
dist: trusty
language: cpp
cache: apt
compiler:
  - gcc
  - clang
env:
  - CONFIG=minimal
  - CONFIG=full
  - CONFIG=full-debug
install:
  - tests/travis/install-build-depends
script:
  - tests/travis/build-and-test
